---
# Got the URL from
# https://www.percona.com/doc/percona-repo-config/percona-release.html
- name: Install percona-release
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Install Percona-XtraDB-Cluster
  yum:
    name: Percona-XtraDB-Cluster-{{ mysql_pkg_version }}-{{ mysql_version }}
    state: present

- name: Install Python Dependencies
  yum:
    name: MySQL-python
    state: present

- name: Enable and start mysql
  service:
    name: mysql
    enabled: yes
    state: started

- name: Change root Password
  mysql_user:
    name: root
    password: "{{ lookup('password', playbook_dir + '/root_pw', length=16) }}"

- name: Create /root/.my.cnf
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf

- name: Set secure_auth=0
  copy:
    dest: /etc/my.cnf.d/secure_auth.cnf
    content: "[mysqld]\nsecure_auth=0\n"
  notify: restart mysql
